blank_issues_enabled: false
contact_links:
  - name: Mullvad VPN Support
    url: https://mullvad.net/help
    about: Please contact support@mullvadvpn.net for account, specific servers or service issues.
