/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

static const char* kBaseFonts[] = {
    "Arial",
    "Cambria Math",
    "Consolas",
    "Courier New",
    "Georgia",
    "Lucida Console",
    "Malgun Gothic",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft YaHei",
    "MS Gothic",
    "MS PGothic",
    "MV Boli",
    "Segoe UI",
    "SimSun",
    "Sylfaen",
    "Tahoma",
    "Times New Roman",
    "Verdana",
};
